"""followers

Revision ID: 521100d4326c
Revises: 31f730d75448
Create Date: 2022-02-17 22:23:12.457289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521100d4326c'
down_revision = '31f730d75448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
